spring:
    application:
        name: producer

server:
    port: 9009

eureka:
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/