spring:
  application:
    name: consumer

server:
  port: 8091

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/